//! Emit the authoritative list of wire method names the crate exposes.
//!
//! The completeness gate in `livetest` needs the exact set of API methods so a
//! newly generated method with no owning area fails the build. That set is the
//! wire strings the generated `Client` actually calls, so this reads them from
//! `src/generated.rs` rather than the WSDL: it captures what the crate exposes,
//! not merely what the schema declares.

use std::fs;

use syn::{Expr, ExprLit, ImplItem, Item, Lit, Stmt};

use crate::repo_root;

/// The `@generated` file `livetest` compiles in, holding the wire names.
const OUT_REL: &str = "livetest/src/wire_methods.rs";

pub fn cmd_dump_methods() -> Result<(), String> {
    let root = repo_root();
    let generated = root.join("src").join("generated.rs");
    let text =
        fs::read_to_string(&generated).map_err(|e| format!("read {}: {e}", generated.display()))?;
    let file = syn::parse_file(&text).map_err(|e| format!("parse {}: {e}", generated.display()))?;

    let mut methods = wire_methods(&file);
    methods.sort();
    methods.dedup();

    let out_path = root.join(OUT_REL);
    fs::write(&out_path, render(&methods))
        .map_err(|e| format!("write {}: {e}", out_path.display()))?;
    println!(
        "wrote {} ({} wire methods)",
        out_path.display(),
        methods.len()
    );

    Ok(())
}

/// Collect the wire string passed to `self.call_raw("...", ..)` in each
/// `*_raw` method of the `impl Client` block. The `_raw` variant is unique per
/// operation, so it names every method once with no `call`/`call_raw` doubling.
fn wire_methods(file: &syn::File) -> Vec<String> {
    let mut out = Vec::new();
    for item in &file.items {
        let Item::Impl(imp) = item else {
            continue;
        };

        for impl_item in &imp.items {
            let ImplItem::Fn(func) = impl_item else {
                continue;
            };

            if !func.sig.ident.to_string().ends_with("_raw") {
                continue;
            }

            if let Some(wire) = first_call_raw_literal(&func.block.stmts) {
                out.push(wire);
            }
        }
    }

    out
}

/// Find the string literal in the first `call_raw("literal", ..)` call within
/// a method body, unwrapping the `.await` and receiver chain.
fn first_call_raw_literal(stmts: &[Stmt]) -> Option<String> {
    for stmt in stmts {
        let expr = match stmt {
            Stmt::Expr(expr, _) => expr,
            _ => continue,
        };

        if let Some(wire) = call_raw_literal(expr) {
            return Some(wire);
        }
    }

    None
}

/// Descend `<expr>.await` / `<recv>.call_raw("wire", ..)` to the wire literal.
fn call_raw_literal(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Await(await_) => call_raw_literal(&await_.base),
        Expr::MethodCall(call) if call.method == "call_raw" => {
            call.args.iter().find_map(string_literal)
        }
        Expr::MethodCall(call) => call_raw_literal(&call.receiver),
        _ => None,
    }
}

fn string_literal(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Lit(ExprLit {
            lit: Lit::Str(s), ..
        }) => Some(s.value()),
        _ => None,
    }
}

fn render(methods: &[String]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo xtask dump-methods` from src/generated.rs.\n\
         // DO NOT EDIT -- regenerate after changing the API surface.\n\
         \n\
         /// Every wire method name the generated `Client` exposes. The\n\
         /// completeness gate asserts the area registry partitions exactly this\n\
         /// set, so a newly generated method with no owning area fails the build.\n\
         pub const WIRE_METHODS: &[&str] = &[\n",
    );
    for m in methods {
        out.push_str(&format!("    {m:?},\n"));
    }

    out.push_str("];\n");
    out
}
