//! Emit the response key paths the typed surface models, per wire method.
//!
//! The live harness needs to know what the crate models in order to notice what
//! it *doesn't*: a key the API returns that no `*Response` field claims
//! deserializes away in silence, because the generated structs do not set
//! `deny_unknown_fields` (and must not -- that is what keeps VoIP.ms adding a
//! field from breaking every caller). The raw-vs-typed probe cannot see such a
//! key either: it only fires when the typed deserialization *fails*.
//!
//! The paths come from the same post-override shapes `cargo xtask gen` renders
//! into `src/generated.rs`, so the table describes the emitted structs by
//! construction. They use the override file's path grammar (`cdr[].ip`), which
//! makes a reported key paste straight into an `additions` entry.

use std::collections::BTreeMap;
use std::fs;

use crate::extract::Shape;

/// The `@generated` file `livetest` compiles in, holding the modeled paths.
const OUT_REL: &str = "livetest/src/response_fields.rs";

/// The segment a dynamic-key map contributes: its keys are data, not schema, so
/// any live key at that position is modeled.
const MAP_WILDCARD: &str = "*";

pub fn cmd_dump_fields() -> Result<(), String> {
    write_table(&crate::load_shapes_for_tools()?)
}

/// Emit the table from shapes already in hand.
///
/// `cargo xtask gen` calls this with the shapes it just rendered `*Response`
/// from, so the two files cannot describe different surfaces. Leaving it to a
/// second command made the documented fix workflow -- paste an `additions`
/// entry, regenerate -- the thing that desynchronized them: the crate would
/// model the new field while the harness kept reporting it on every run.
/// Reject a shape this emitter cannot describe, before anything is written.
///
/// The key diff compares against an object envelope's keys. A root list yields
/// paths starting `[].x`, which cover nothing, and a root scalar yields none at
/// all, which the probe would have to read as "no shape".
/// `response_codegen::emit_struct` has arms for both, so this is reachable the
/// day one appears; refusing beats emitting a table that silently misreports.
///
/// `gen` calls this before rendering, so a shape it cannot serve stops the run
/// rather than leaving `src/generated.rs` written and this table stale, which is
/// the divergence emitting both from one pass exists to rule out.
pub fn validate_roots(shapes: &BTreeMap<String, Shape>) -> Result<(), String> {
    for (method, shape) in shapes {
        if !matches!(shape, Shape::Object(_)) {
            return Err(format!(
                "{method}: response shape root is not an object, which the live \
                 harness's key diff assumes; teach `dump-fields` and `keydiff` \
                 this shape before regenerating"
            ));
        }
    }

    Ok(())
}

pub fn write_table(shapes: &BTreeMap<String, Shape>) -> Result<(), String> {
    validate_roots(shapes)?;

    let mut table: Vec<(String, Vec<String>)> = Vec::new();
    for (method, shape) in shapes {
        let mut paths = Vec::new();
        collect(shape, "", &mut paths);
        paths.sort();
        paths.dedup();
        table.push((method.clone(), paths));
    }

    table.sort_by(|a, b| a.0.cmp(&b.0));

    let out_path = crate::repo_root().join(OUT_REL);
    fs::write(&out_path, render(&table))
        .map_err(|e| format!("write {}: {e}", out_path.display()))?;
    crate::rustfmt_file(&out_path);

    let total: usize = table.iter().map(|(_, p)| p.len()).sum();
    println!(
        "wrote {} ({} methods, {total} modeled paths)",
        out_path.display(),
        table.len(),
    );

    Ok(())
}

/// Walk a shape into the dotted paths of every key it models.
///
/// A list contributes `[]` to its element's prefix and a map contributes `*`,
/// so the emitted path describes a position rather than one live value.
fn collect(shape: &Shape, prefix: &str, out: &mut Vec<String>) {
    match shape {
        Shape::Object(fields) => {
            for (name, inner) in fields {
                let path = join(prefix, name);
                out.push(path.clone());
                collect(inner, &path, out);
            }
        }
        Shape::List(element) => collect(element, &format!("{prefix}[]"), out),
        Shape::Map(value) => {
            let path = join(prefix, MAP_WILDCARD);
            out.push(path.clone());
            collect(value, &path, out);
        }
        Shape::Scalar { .. } => {}
    }
}

fn join(prefix: &str, name: &str) -> String {
    if prefix.is_empty() {
        name.to_string()
    } else {
        format!("{prefix}.{name}")
    }
}

fn render(table: &[(String, Vec<String>)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo xtask gen` from tools/api-responses.json plus\n\
         // tools/api-response-overrides.json, alongside src/generated.rs and from\n\
         // the same shapes. `cargo xtask dump-fields` rebuilds this file alone.\n\
         // DO NOT EDIT -- regenerate after changing the API surface.\n\
         \n\
         /// Every response key path the generated `*Response` types model, per\n\
         /// wire method, sorted by method. A live key matching none of a method's\n\
         /// paths is one the typed surface drops.\n\
         ///\n\
         /// Paths use the override file's grammar so a finding pastes into an\n\
         /// `additions` entry: `field`, `list[].field`, and `map.*` for a\n\
         /// dynamic-key map, whose `*` matches any single live segment.\n\
         pub const RESPONSE_FIELDS: &[(&str, &[&str])] = &[\n",
    );
    for (method, paths) in table {
        out.push_str(&format!("    ({method:?}, &[\n"));
        for path in paths {
            out.push_str(&format!("        {path:?},\n"));
        }

        out.push_str("    ]),\n");
    }

    out.push_str(
        r#"];

/// The modeled paths for one wire method, or `None` when the method has no
/// typed response shape at all.
pub fn modeled_paths(method: &str) -> Option<&'static [&'static str]> {
    RESPONSE_FIELDS
        .binary_search_by(|(name, _)| (*name).cmp(method))
        .ok()
        .map(|i| RESPONSE_FIELDS[i].1)
}
"#,
    );

    out
}
