//! Code generator for `src/generated.rs`.
//!
//! For each WSDL `<operation>`, emits:
//!   * A `*Params` request struct with one `Option<T>` field per WSDL input
//!     element (`api_username`/`api_password` excluded; they come from the
//!     `Client`).
//!   * A method on `Client` that calls the underlying REST endpoint.
//!
//! Run from the repository root:
//!     cargo xtask gen

use roxmltree::{Document, Node};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};
use std::{env, fs, io};

const XSD_NS: &str = "http://www.w3.org/2001/XMLSchema";

/// Acronyms recognized when converting camelCase wire names to snake_case
/// Rust identifiers. The tokenizer tries the longest match first.
const ACRONYMS: &[&str] = &[
    "DISAs", "DIDs", "IVRs", "VPRIs", "URIs", "CDRs", "IPs", "PRIs", "DID", "IVR", "LNP", "CDR",
    "SIP", "SMS", "USA", "CAN", "FAX", "CNAM", "MMS", "DISA", "RTP", "DTMF", "ANI", "API", "PIN",
    "NAT", "URL", "CSV", "JSON", "XML", "PRI", "URI", "VPRI", "vPRI", "PDF", "POP", "IP", "TZ",
    "DST", "US", "ID",
];

/// Fields that come from the `Client`, not the per-method request struct.
const CLIENT_FIELDS: &[&str] = &["api_username", "api_password"];

fn xsd_to_rust(t: &str) -> &'static str {
    match t {
        "xsd:string" => "String",
        "xsd:integer" => "i64",
        "xsd:boolean" => "bool",
        "xsd:decimal" => "f64",
        _ => "String",
    }
}

fn acronyms_sorted() -> Vec<&'static str> {
    let mut v: Vec<&'static str> = ACRONYMS.to_vec();
    v.sort_by_key(|s| std::cmp::Reverse(s.len()));
    v
}

fn tokenize(s: &str, acronyms: &[&str]) -> Vec<String> {
    let bytes = s.as_bytes();
    let n = bytes.len();
    let mut tokens: Vec<String> = Vec::new();
    let mut cur = String::new();
    let mut i = 0;
    while i < n {
        let rest = &s[i..];
        if let Some(a) = acronyms.iter().find(|a| rest.starts_with(**a)) {
            if !cur.is_empty() {
                tokens.push(std::mem::take(&mut cur));
            }
            tokens.push(a.to_ascii_lowercase());
            i += a.len();
            continue;
        }
        let c = bytes[i] as char;
        if c.is_ascii_uppercase() {
            if !cur.is_empty() {
                tokens.push(std::mem::take(&mut cur));
            }
            cur.push(c.to_ascii_lowercase());
        } else {
            cur.push(c);
        }
        i += 1;
    }
    if !cur.is_empty() {
        tokens.push(cur);
    }
    tokens
}

fn camel_to_snake(s: &str, acronyms: &[&str]) -> String {
    tokenize(s, acronyms).join("_")
}

fn camel_to_pascal(s: &str, acronyms: &[&str]) -> String {
    tokenize(s, acronyms)
        .into_iter()
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

#[derive(Debug)]
struct Wsdl {
    operations: Vec<String>,
    types: std::collections::HashMap<String, Vec<(String, String)>>,
}

fn parse_wsdl(text: &str) -> Result<Wsdl, String> {
    let doc = Document::parse(text).map_err(|e| format!("parse WSDL: {e}"))?;

    let mut types = std::collections::HashMap::new();
    for ct in doc.descendants().filter(|n| is_xsd(n, "complexType")) {
        let Some(name) = ct.attribute("name") else {
            continue;
        };
        let mut fields: Vec<(String, String)> = Vec::new();
        if let Some(seq) = ct.children().find(|n| is_xsd(n, "sequence")) {
            for el in seq.children().filter(|n| is_xsd(n, "element")) {
                if let (Some(fname), Some(ftype)) = (el.attribute("name"), el.attribute("type")) {
                    fields.push((fname.to_string(), ftype.to_string()));
                }
            }
        }
        types.insert(name.to_string(), fields);
    }

    let mut seen = BTreeSet::new();
    for op in doc
        .descendants()
        .filter(|n| n.tag_name().name() == "operation")
    {
        if let Some(name) = op.attribute("name") {
            seen.insert(name.to_string());
        }
    }
    let operations: Vec<String> = seen.into_iter().collect();

    Ok(Wsdl { operations, types })
}

fn is_xsd(n: &Node, local: &str) -> bool {
    n.tag_name().name() == local && n.tag_name().namespace() == Some(XSD_NS)
}

/// `type` is a Rust keyword; rename to `r#type`.
fn rust_field_name(name: &str) -> String {
    if name == "type" {
        "r#type".to_string()
    } else {
        name.to_string()
    }
}

fn emit(wsdl: &Wsdl) -> String {
    let acronyms = acronyms_sorted();
    let mut out = String::new();
    out.push_str(
        "// @generated by xtask from tools/server.wsdl.\n\
         // DO NOT EDIT — regenerate with `cargo xtask gen`.\n\
         \n\
         #![allow(clippy::too_many_arguments)]\n\
         #![allow(non_snake_case)]\n\
         \n\
         use serde::de::DeserializeOwned;\n\
         use serde::Serialize;\n\
         use serde_json::Value;\n\
         \n\
         use crate::client::Client;\n\
         use crate::error::Result;\n",
    );

    for op in &wsdl.operations {
        let struct_name = format!("{}Params", camel_to_pascal(op, &acronyms));
        let input_name = format!("{op}Input");
        let empty = Vec::new();
        let fields = wsdl.types.get(&input_name).unwrap_or(&empty);

        out.push_str(&format!(
            "\n/// Parameters for [`Client::{}`] (wire method `{op}`).\n",
            camel_to_snake(op, &acronyms),
        ));
        out.push_str("#[derive(Debug, Default, Clone, Serialize)]\n");
        let body_fields: Vec<&(String, String)> = fields
            .iter()
            .filter(|(n, _)| !CLIENT_FIELDS.contains(&n.as_str()))
            .collect();
        if body_fields.is_empty() {
            out.push_str(&format!("pub struct {struct_name} {{}}\n"));
            continue;
        }
        out.push_str(&format!("pub struct {struct_name} {{\n"));
        for (fname, ftype) in body_fields {
            let rust_ty = xsd_to_rust(ftype);
            let ident = rust_field_name(fname);
            out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
            out.push_str(&format!("    pub {ident}: Option<{rust_ty}>,\n"));
        }
        out.push_str("}\n");
    }

    out.push_str("\nimpl Client {\n");
    for op in &wsdl.operations {
        let method = camel_to_snake(op, &acronyms);
        let struct_name = format!("{}Params", camel_to_pascal(op, &acronyms));
        out.push_str(&format!(
            "    /// Call the `{op}` API method.\n    \
             pub async fn {method}(&self, params: &{struct_name}) -> Result<Value> {{\n        \
                self.call(\"{op}\", params).await\n    \
             }}\n\n\
             /// Call the `{op}` API method and deserialize the response body into `T`.\n    \
             pub async fn {method}_typed<T>(&self, params: &{struct_name}) -> Result<T>\n    \
             where\n    \
                 T: DeserializeOwned,\n    \
             {{\n        \
                 self.call_typed(\"{op}\", params).await\n    \
             }}\n\n"
        ));
    }
    out.push_str("}\n");
    out
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent")
        .to_path_buf()
}

fn cmd_gen() -> Result<(), String> {
    let root = repo_root();
    let wsdl_path = root.join("tools").join("server.wsdl");
    let out_path = root.join("src").join("generated.rs");

    let text =
        fs::read_to_string(&wsdl_path).map_err(|e| format!("read {}: {e}", wsdl_path.display()))?;
    let wsdl = parse_wsdl(&text)?;

    // Sanity checks (warnings only, mirror gen.py).
    let missing: Vec<&String> = wsdl
        .operations
        .iter()
        .filter(|op| !wsdl.types.contains_key(&format!("{op}Input")))
        .collect();
    if !missing.is_empty() {
        eprintln!(
            "warning: {} operations missing input type: {:?}",
            missing.len(),
            &missing[..missing.len().min(5)],
        );
    }

    let mut unknown = BTreeSet::new();
    for op in &wsdl.operations {
        if let Some(fields) = wsdl.types.get(&format!("{op}Input")) {
            for (_, t) in fields {
                if !matches!(
                    t.as_str(),
                    "xsd:string" | "xsd:integer" | "xsd:boolean" | "xsd:decimal"
                ) {
                    unknown.insert(t.clone());
                }
            }
        }
    }
    if !unknown.is_empty() {
        eprintln!("warning: unmapped XSD types: {unknown:?}");
    }

    let rendered = emit(&wsdl);
    fs::write(&out_path, &rendered).map_err(|e| format!("write {}: {e}", out_path.display()))?;
    println!(
        "wrote {} ({} methods)",
        out_path.display(),
        wsdl.operations.len(),
    );

    match Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&out_path)
        .status()
    {
        Ok(s) if s.success() => {}
        Ok(s) => eprintln!("warning: rustfmt exited with {s}; run `cargo fmt` manually"),
        Err(e) if e.kind() == io::ErrorKind::NotFound => {
            eprintln!("warning: rustfmt not found on PATH; run `cargo fmt` manually");
        }
        Err(e) => eprintln!("warning: rustfmt failed ({e}); run `cargo fmt` manually"),
    }
    Ok(())
}

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();
    let cmd = args.first().map(String::as_str).unwrap_or("gen");
    let res = match cmd {
        "gen" => cmd_gen(),
        other => Err(format!("unknown subcommand `{other}` (expected `gen`)")),
    };
    match res {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}
