#!/usr/bin/env python3
"""Generate src/generated.rs from tools/server.wsdl.

For each WSDL <operation>, emits:
  * A `*Params` request struct with one `Option<T>` field per WSDL input
    element (api_username/api_password excluded; they come from the Client).
  * A method on `Client` that calls the underlying REST endpoint.

Run from the repository root:
    python3 tools/gen.py
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

WSDL = Path(__file__).resolve().parent / "server.wsdl"
OUT = Path(__file__).resolve().parent.parent / "src" / "generated.rs"

XSD_NS = "{http://www.w3.org/2001/XMLSchema}"

# Acronyms recognised when converting camelCase wire names to snake_case Rust
# identifiers. Order doesn't matter; the tokenizer tries the longest match first.
ACRONYMS = sorted(
    {
        "DISAs",
        "DIDs", "IVRs", "VPRIs", "URIs", "CDRs", "IPs", "PRIs",
        "DID", "IVR", "LNP", "CDR", "SIP", "SMS", "USA", "CAN", "FAX",
        "CNAM", "MMS", "DISA", "RTP", "DTMF", "ANI", "API", "PIN",
        "NAT", "URL", "CSV", "JSON", "XML", "PRI", "URI", "VPRI", "vPRI",
        "PDF", "POP",
        "IP", "TZ", "DST", "US", "ID",
    },
    key=lambda s: -len(s),
)

# Fields that come from the Client, not the per-method request struct.
CLIENT_FIELDS = {"api_username", "api_password"}

XSD_TO_RUST = {
    "xsd:string": "String",
    "xsd:integer": "i64",
    "xsd:boolean": "bool",
    "xsd:decimal": "f64",
}


def tokenize(s: str) -> list[str]:
    tokens: list[str] = []
    cur = ""
    i = 0
    n = len(s)
    while i < n:
        matched = next((a for a in ACRONYMS if s.startswith(a, i)), None)
        if matched is not None:
            if cur:
                tokens.append(cur)
                cur = ""
            tokens.append(matched.lower())
            i += len(matched)
            continue
        c = s[i]
        if c.isupper():
            if cur:
                tokens.append(cur)
                cur = ""
            cur = c.lower()
        else:
            cur += c
        i += 1
    if cur:
        tokens.append(cur)
    return tokens


def camel_to_snake(s: str) -> str:
    return "_".join(tokenize(s))


def camel_to_pascal(s: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in tokenize(s))


def parse_wsdl(path: Path):
    """Return (operations, types). operations: ordered list of wire names.
    types: dict[name -> list[(field_name, xsd_type)]] for *Input complex types."""
    text = path.read_text(encoding="utf-8")
    root = ET.fromstring(text)

    types: dict[str, list[tuple[str, str]]] = {}
    for ct in root.iter(f"{XSD_NS}complexType"):
        name = ct.get("name")
        if name is None:
            continue
        seq = ct.find(f"{XSD_NS}sequence")
        if seq is None:
            types[name] = []
            continue
        fields = []
        for el in seq.findall(f"{XSD_NS}element"):
            fields.append((el.get("name"), el.get("type")))
        types[name] = fields

    operations: list[str] = []
    seen: set[str] = set()
    for m in re.finditer(r'<operation name="([^"]+)">', text):
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        operations.append(name)
    operations.sort()
    return operations, types


def rust_field_name(name: str) -> tuple[str, str | None]:
    """Return (ident, optional_serde_rename).

    `type` is a Rust keyword; rename to `r#type` and instruct serde to keep
    the wire name.
    """
    if name == "type":
        return "r#type", None
    return name, None


def emit(operations: list[str], types: dict[str, list[tuple[str, str]]]) -> str:
    out: list[str] = []
    out.append(
        "// @generated by tools/gen.py from tools/server.wsdl.\n"
        "// DO NOT EDIT — regenerate with `python3 tools/gen.py`.\n"
        "\n"
        "#![allow(clippy::too_many_arguments)]\n"
        "#![allow(non_snake_case)]\n"
        "\n"
        "use serde::Serialize;\n"
        "use serde_json::Value;\n"
        "\n"
        "use crate::client::Client;\n"
        "use crate::error::Result;\n"
    )

    # Struct definitions
    for op in operations:
        struct_name = camel_to_pascal(op) + "Params"
        input_name = f"{op}Input"
        fields = types.get(input_name, [])

        out.append(
            f"\n/// Parameters for [`Client::{camel_to_snake(op)}`] "
            f"(wire method `{op}`).\n"
        )
        out.append("#[derive(Debug, Default, Clone, Serialize)]\n")
        body_fields = [f for f in fields if f[0] not in CLIENT_FIELDS]
        if not body_fields:
            out.append(f"pub struct {struct_name} {{}}\n")
            continue
        out.append(f"pub struct {struct_name} {{\n")
        for fname, ftype in body_fields:
            rust_ty = XSD_TO_RUST.get(ftype, "String")
            ident, _ = rust_field_name(fname)
            out.append("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
            out.append(f"    pub {ident}: Option<{rust_ty}>,\n")
        out.append("}\n")

    # Client impl block with one method per operation
    out.append("\nimpl Client {\n")
    for op in operations:
        method = camel_to_snake(op)
        struct_name = camel_to_pascal(op) + "Params"
        out.append(
            f"    /// Call the `{op}` API method.\n"
            f"    pub async fn {method}(&self, params: &{struct_name}) -> Result<Value> {{\n"
            f"        self.call(\"{op}\", params).await\n"
            f"    }}\n\n"
        )
    out.append("}\n")
    return "".join(out)


def main() -> int:
    operations, types = parse_wsdl(WSDL)

    # Sanity check: every operation has a matching *Input complex type
    missing = [op for op in operations if f"{op}Input" not in types]
    if missing:
        print(f"warning: {len(missing)} operations missing input type: {missing[:5]}", file=sys.stderr)

    # Sanity check: every XSD type is one we know about
    unknown: set[str] = set()
    for op in operations:
        for _, t in types.get(f"{op}Input", []):
            if t not in XSD_TO_RUST:
                unknown.add(t)
    if unknown:
        print(f"warning: unmapped XSD types: {unknown}", file=sys.stderr)

    OUT.write_text(emit(operations, types), encoding="utf-8")
    print(f"wrote {OUT} ({len(operations)} methods)")

    # Format with rustfmt so the generated file matches `cargo fmt --check`.
    try:
        import subprocess

        subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as e:
        print(f"warning: rustfmt failed ({e}); run `cargo fmt` manually", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
